{% set name = "mpv" %}
{% set version = "0.38.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mpv-player/mpv/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 86d9ef40b6058732f67b46d0bbda24a074fae860b3eaae05bab3145041303066

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - meson
    - ninja
    - cmake
    - pkg-config
    - docutils
  host:
    - ffmpeg
    - libjpeg-turbo
    - libiconv
    - libdrm  # [linux]
    - libarchive
    - libass
    - lcms2
    - uchardet  # [linux]
    - vapoursynth
    - yt-dlp
    - xz
    - zlib
  run:
    - uchardet  # [linux]
    - vapoursynth
    - yt-dlp

test:
  commands:
    - mpv --help

about:
  home: https://mpv.io
  license: GPL-2.0-or-later
  license_file: LICENSE.GPL
  summary: 'Media player based on MPlayer and mplayer2'
  description: |
    MPV is a free, open-source, and cross-platform media player based on 
    MPlayer and mplayer2. It supports a wide variety of video file formats, 
    audio and video codecs, and subtitle types.

extra:
  recipe-maintainers:
    - Tobias-Fischer
